version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plzify
    ports:
      - 5432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data
